# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       wayland-wsegl

# >> macros
# << macros

Summary:    WSEGL for Wayland
Version:    0.1
Release:    1
Group:      Applications/Engineering
License:    Undecided
URL:        http://foobar.com
Source0:    %{name}-%{version}.tar.gz
Source100:  wayland-wsegl.yaml
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(libffi)
BuildRequires:  pkgconfig(wayland-client)
BuildRequires:  pkgconfig(wayland-server)
BuildRequires:  ti-omap3-sgx-devel

%description
- Something


%package eglext
Summary:    wayland devel library
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description eglext
devel files for wayland

%package eglext-devel
Summary:    wayland devel library
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   wayland-wsegl-eglext

%description eglext-devel
devel files for wayland

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
# >> files
%{_libdir}/waylandwsegl.so
%{_libdir}/libwayland-egl.so.1.0
%{_libdir}/libwayland-egl.so.1
# << files

%files eglext
%defattr(-,root,root,-)
# >> files eglext
# << files eglext

%files eglext-devel
%defattr(-,root,root,-)
# >> files eglext-devel
# << files eglext-devel
