#
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
#
# >> macros
# << macros

Name:       wayland-wsegl
Summary:    WSEGL for Wayland
Version:    0.1
Release:    1
Group:      Applications/Engineering
License:    Undecided
URL:        http://foobar.com
Source0:    %{name}-%{version}.tar.gz
Source100:  wayland-wsegl.yaml
BuildRequires:  pkgconfig(wayland-client)
BuildRequires:  pkgconfig(wayland-server)
BuildRequires:  ti-omap3-sgx-devel
BuildRequires:  libffi-devel

%description
- Something

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post





%post -p /sbin/ldconfig
%postun -p /sbin/ldconfig







%files
%defattr(-,root,root,-)
# >> files
%{_libdir}/waylandwsegl.so
%{_libdir}/libwayland-egl.so.1.0
%{_libdir}/libwayland-egl.so.1
# << files
